title: Alison
description: A description of your site
baseurl: ""
url: "https://SeowonYang.github.io"
remote_theme: just-the-docs/just-the-docs
search_enabled: true

# Navigation 설정
just_the_docs:
    navigation:
        - title: "Home"
          url: /
          nav_order: 1
        - title: "Categories"
          nav_order: 2
          children:
              - title: "Personal"
                url: /personal/
              - title: "Dev"
                url: /dev/
              - title: "Math"
                url: /mathe/

# 플러그인 설정
plugins:
    - jekyll-remote-theme # 원격 테마를 사용하기 위한 플러그인
    - jekyll-seo-tag # SEO 태그 지원
    - jekyll-archives

# 빌드 설정
markdown: kramdown

defaults:
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
          categories: ["personal", "dev", "math"]

jekyll-archives:
    enabled:
        - categories
    layout: archive
    permalinks:
        categories: /categories/:name/
