baseURL = "https://SeowonYang.github.io/"
languageCode = "ko-kr"
title = "Yang Log"
theme = "hugo-PaperMod"

[params]
  enableSearch = true

[[menu.main]]
  name = "Archive"
  url = "/archives/"
  weight = 10

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 20